export enum AddOnTypeEnum {
  COLD_WATER = 'COLD_WATER',
  HOT_WATER = 'HOT_WATER',
  DETERGENT = 'DETERGENT',
  SOFTENER = 'SOFTENER',
  DRYING_TIME_MINUTE = 'DRYING_TIME_MINUTE',
  OTHER = 'OTHER',
}
